export const FETCH_ART_REQUEST = 'FETCH_ART_REQUEST';
export const FETCH_ART_SUCCESS = 'FETCH_ART_SUCCESS';
export const FETCH_ART_FAIL = 'FETCH_ART_FAIL';
export const FETCH_TOTAL = 'FETCH_TOTAL';
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_FAIL = "POST_COMMENT_FAIL";
export const FETCH_COMMENT_REQUEST = 'FETCH_COMMENT_REQUEST';
